# Variables passed to this playbook:
# -         'etcdremove': list of instances that'll be removed from the etcd cluster.
# -         'noderemove': list of instances that'll be removed from the node category.
# -         'masterremove': list of instances that'll be removed from the master category.
# Note: This playbook is called *PRIOR* to removal from the Ansible Inventory.
