# Variables passed to this playbook:
# -         'etcdremove': list of instances that'll be removed from the etcd cluster.
# -         'noderemove': list of instances that'll be removed from the node category.
# -         'masterremove': list of instances that'll be removed from the master category.
# Note: This playbook is called *PRIOR* to removal from the Ansible Inventory.
---
- hosts: all
  tasks:
  - block:
    - debug:
      msg: running pre-scaledown for all
- hosts: masters
  tasks:
  - block:
    - debug:
      msg: running pre-scaledown for masters
    when: masterremove | length > 0
- hosts: etcd
  tasks:
  - block:
    - debug:
      msg: running pre-scaledown for etcd
    - include_tasks: remove_node_from_etcd_cluster.yml
      msg: running pre-scaledown for etcd
    when: etcdremove | length > 0

- hosts: nodes
  tasks:
  - block:
    - debug:
      msg: running pre-scaledown for nodes
    when: noderemove | length > 0