# AWS QuickStart OpenShift Installation
#
# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=root
#openshift_deployment_type=openshift-enterprise
openshift_deployment_type=origin
openshift_hosted_router_wait=False
openshift_hosted_registry_wait=False
debug_level=0
containerized=false
openshift_master_cluster_method=native
openshift_disable_check=docker_storage
